version: "3.7"
services:
  acervo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    networks:
      - api
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: acervo
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - api
    volumes:
      - "./datavolume:/var/lib/mysql"
volumes:
  datavolume:
networks:
  api:
    driver: bridge